### PR TITLE
chore: Add snapshot path to error

### LINKED ISSUE #1941: Missing debug-info on paths when backup path structure does not exist
Hello,
I had to configure everything from terminal - no UI. It took me a few hours to construct the necessary path for backups because of very confusing docs and lack of my understanding of the app. Can you please add the erroneous backup target path into debug output? Currently that is how it looks:

_notify-send -t 30000 Back In Time (admin) : daily Can't find snapshots folder. If it is on a removable drive please plug it. Waiting 30 seconds.
Failed to execute child process “dbus-launch” (No such file or directory)
DEBUG: [common/snapshots.py:747 backup] Cannot start snapshot yet: target directory not accessible. Waiting 1s._

Please add the full path in the error message that caused the error, that is a simple change, but can help a lot, e.g:

_notify-send -t 30000 Back In Time (admin) : daily Can't find snapshots folder '/backup/backintime/myserver/root/1'. If it is on a removable drive please plug it. Waiting 30 seconds._

Thanks,
Igor.

### PR DESCRIPTION
**Pull request by s4moore**
Added the path of the missing directory to the snapshot error message to aid in debugging for users

Close #1941

### CODE REVIEW

**Review by buhtz — CHANGES_REQUESTED** [review]
Hello Samuel,
On behalf of the team, thank you for your contribution and taking the time to improve Back In Time. We appreciate it. Your PR is a good start.

As you might see in the TravisCI output, the test suite offers two failing tests which are related to each other:

- `FAILED test/test_backup.py::TestBackup::test_cant_backup - AttributeError: 'Snapshots' object has no attribute 'snapshotsFullPath'`
- `snapshots.py:832:50: E1101: Instance of 'Snapshots' has no 'snapshotsFullPath' member (no-member)`

We recommend to run BIT and its test suite on your local system before submitting a PR. In this case you would might have seen these errors first.

I am sure you will find a solution for these error messages. Don't hesitate to ask if you need more assistance.

Regards,
Christian

**Comment by s4moore** [comment]
Hello Christian,

Thank you for for your patience. I have updated the code to pull the snapshotsFullPath from the config instance.

I have run the test suite and there are no issues aside from some unrelated warnings. Please let me know if all okay.

Thanks,
Sam

**Review by buhtz — APPROVED** [review]
Hello Samuel,
thank you for fixing this.
I just added minor modifications regarding to our translation team. The code might be ugly but separating the translatable stings this way makes the job easier for our translators.

Regards,
Christian

**Comment by s4moore** [comment]
Okay great, sorry it's my first time working with translators.. So is that all done then? Is there anything else I need to do? (It's also my first time contributing 😬 )

I was thinking to try to solve "Highlight and report non-existent include directories #1910" next unless you have a better suggestion?

**Comment by buhtz** [comment]
> Okay great, sorry it's my first time working with translators..

No need to be sorry. Dealing with translators and their strings is not easy and need a lot of experience including trail and error. I would not expect a contributor to know things like this.

> So is that all done then? Is there anything else I need to do? (It's also my first time contributing 😬 )

No, everything is fine. You might see the blue check mark and "1 approval". This is my mark that your PR is fine and ready to merge. I also added the label "PR: Merge after creative break". that means the same. We usually wait some days before merging even if the PR seems to be finished. It is often a good idea to sleep over it one night or more no matter how simple a PR looks like.

To find out how we usually tread PRs please read
["What happens after you opened a PullRequest (PR)?"](https://github.com/bit-team/backintime/blob/dev/CONTRIBUTING.md#what-happens-after-you-opened-a-pull-request-PR).

> I was thinking to try to solve "Highlight and report non-existent include directories #1910" next unless you have a better suggestion?

Mhm... Dealing with GUI stuff is not easy because the code base "smells" and is not well organized.

What is your native language? You might want to contribute translations?

Maybe #1105, #1018

**Comment by s4moore** [comment]
My native language is English so I guess that will not be too much help but let me know if I'm wrong on that...

I will take a look at #1105

**Comment by buhtz** [comment]
> My native language is English so I guess that will not be too much help but let me know if I'm wrong on that...

Ah, OK. Just let me know if you find English that could be improved. Open an issue for this or directly edit the sources and provide the correction with an PR.

> I will take a look at #1105

Good choice I think.

**Pull request merged**
