### PR TITLE
Fix typo in Russian translation

### PR DESCRIPTION
**Pull request by bigscoop**
Changed wrong translation

### CODE REVIEW

**Comment by buhtz** [comment]
Dear bigscoop,
thank you very much for your contribution. We will integrate it as soon as possible.

The situation is a bit complicated.
 - The mo files in this repository are just mirrored copies not intended to be modified.
 - The original sources of the language files do exist on [Launchpad](https://translations.launchpad.net/backintime).
 - But we also have problems with Launchpad an will migrate to another translation platform more comfortable I hope. I currently play around with Weblate hostet at Codeberg.

Because of that I'll keep this PR open as a reminder and add your modification after we migrated to the new platform. Your contribution won't be lost.

**Comment by buhtz** [comment]
Dear Dimitri,
I setup a new translation system using Weblate (hosted on [Codeberg.org](https://coderberg.org).

I'm interested in your users perspective. If you can find the time it would help me a lot.

Please go to the [platform](https://translate.codeberg.org/projects/backintime/common/) and do your translation again.
You even don't have to create an extra login. It is also possible to just "suggest" translations.

**Comment by bigscoop** [comment]
Thanks. The translation there is blocked for now, I'll try later

**Comment by buhtz** [comment]
> Thanks. The translation there is blocked for now, I'll try later

The Block is on my fault. It will kept blocked for the next days. I have to figuring out some details.

**Comment by bigscoop** [comment]
Ok, translation done, thanks!

**Comment by buhtz** [comment]
I'll keep this open for myself as a reminder because the migration to Weblate isn't finalized yet.
Thanks for your help.

**Comment by buhtz** [comment]
Dear Dimitri,

our [Weblate translation platform](https://translate.codeberg.org/projects/backintime/common/) is no setup and updated to the latest state of Back In Time including ease some of the strings (PR #1448) to translate.

If you like it would be great if you could look into the Russian translations. Please let me also know if I should add you to the `TRANSLATIONS' file so you appear as a translator in the About dialog.

Kind
Christian

**Pull request closed without merging**
