### PR TITLE
chore: Debug output and translation recommendations

### PR DESCRIPTION
**Pull request by buhtz**
My intention was to reduce the debug output at all. But I wasn't sure about all the Qt and Keyring related stuff. So in the end I didn't change so much.
Additionally I improved the contribution docu about how to deal with translatable strings.

### CODE REVIEW

**Comment by daviewales** [comment]
Looks OK.

**Comment by buhtz** [comment]
Thank you for the review.
If you are interested in pimping up your profile, you an use the "Review Changes" button in the "Files changed" section/tab.
image

This might influence this graphic in your profile.
image

Or maybe you don't see that button because of permission settings?

**Comment by daviewales** [comment]
Thanks. I usually use that when I'm going to make a bunch of suggestions, and want to send them all at once. To be honest my profile is not a consideration! I didn't have any suggestions for this one, but wanted to let you know I'd looked.

**Comment by buhtz** [comment]
> To be honest my profile is not a consideration!

Heartwarming. 😄 Sometimes I have to deal with profile-pimpers.

**Pull request merged**
