### PR TITLE
Fixed test with polluted output by gtk-warning messages

### PR DESCRIPTION
**Pull request by KaibutsuX**
Related to #1409

### CODE REVIEW

**Comment by buhtz** [comment]
Dear Kaibutsu,
thanks in advance for your contribution.

Some base rules for your next PRs
 - Please work on `dev` branch instead of `main`. It means create your fix-branches based on `dev` because `dev` does represent the latest development state. `main` does only represent the releases.
 - Please try to follow PEP8 code formatting rules.
 - Please see [Contribution-section](https://github.com/bit-team/backintime/blob/main/README.md#contribute) in our README. Note for myself: Add the how-to-branch-PR-etc-infos there.

About your approach:
The contain-lines-method IMHO does reinvent the wheel. There are more pythonic solutions for this. But no matter about the implementation details the whole test should be refactored. But I won't find the time for it in the next days. It will take a bit longer.

**Comment by buhtz** [comment]
Alternative approach #1412

**Comment by aryoda** [comment]
We basically have to decide now if we want to check the actual output of our unit tests

1. against expected lines only, ignoring all others (= filter keeps expected outputs only)

2. or remove all well-known unwanted output before checking the expected output  (= filter removes well-known unwanted outputs)

Impact:

"1." is more resilient against any polluted output (even output we do not know today) but may succeed even if one the "polluted" outputs should make the test fail

"2." is quite defensive - every unexpected polluted output makes the test fail and requires to change the unit test to filter (remove) this output. But is ensures that every  unexpected output is checked by human for its severityl

**Comment by buhtz** [comment]
Because the refactoring of that specific test is a far away task I'm not in a hurry to decide it now.

1. and 2. are both workarounds and not the right approach for high quality tests no matter where in the test pyramid they are located.

When the log output of the application is well structured and separated between diagnostic/debug and user output then 1. is the choice. But what is "user output" in context of BIT? Just a rhetoric question! There are so many topics behind it I won't open yet. :smile: 

*EDIT*: I have to say that I'm currently much influenced by the book [_Unit Testing Principles, Practices, and Patterns_ (by Vladimir Khorikov)](https://www.manning.com/books/unit-testing).

**Comment by KaibutsuX** [comment]
Without deep-diving into all of the tests and seeing what else there is, I would initially argue against tests that parse the output of a subprocess.

Unless backintime is packing its own compiled rsync (I assume it just shells it out to the system), I don't see that much value or stability in checking stdout/stderr for expected logs. What if I have a custom built rsync or custom logging that generates custom log entries?

I would think the better test would be testing actual behavior and verifying expected/ignored/failed files end up or don't in a target sandbox. Assuming those tests already exist, I'm not sure how much value this test actually provides.

**Comment by aryoda** [comment]
> Unless backintime is packing its own compiled rsync (I assume it just shells it out to the system),
> I don't see that much value or stability in checking stdout/stderr for expected logs.
> [...]
> I would think the better test would be testing actual behavior and verifying expected/ignored/failed files
> end up or don't in a target sandbox

Yes, I see your points.

We (the newly formed DEV team of BiT) do currently have only limited "man power" to fix all
open issues and improve e.g. those testing things.

Currently we are focusing on stabilizing BiT (no new features or major changes that could break anything.

So any help is welcome (THX a lot for your PR BTW)!

**Comment by buhtz** [comment]
> I would think the better test would be testing actual behavior and verifying expected/ignored/failed files end up or don't in a target sandbox.

That is the _classical school_ of unit testing you describing and I agree here.  Some weeks ago I was more a _london school_ type but the book of [Vladimir Khorikov](https://www.manning.com/books/unit-testing) convinced me. :smile: 

Have you seen our [development mailing list](https://mail.python.org/mailman3/lists/bit-dev.python.org/)? Please feel free to join!

I have a big list of code parts and ideas how to refactor them. Very big and long list. One point is manpower as @aryoda pointed out and the other is fear of destroying things.

**Comment by buhtz** [comment]
Replaced by #1412 

Thanks again for contribution and testing. We are wide open for more contributions of any kind.

**Comment by buhtz** [comment]
Dear @KaibutsuX ,
I couldn't find an address to get in contact with you.

In regards to your valuable PR would you like to be more involved in Back In Time development? Please feel free to contact me or the team.

**Comment by KaibutsuX** [comment]
@buhtz sure, I would be open to more involvement.

**Pull request closed without merging**
