### PR TITLE
fix(gui): remove ExtraMouseButtonEventFilter when closing (#1095)

### LINKED ISSUE #1095: Segmentation fault on Exit (Qt)
We got a downstream bug report that backintime fails with a segmentation fault, whenever it is closed in the current fedora rawhide.
Please see the downstream bug report at 
https://bugzilla.redhat.com/show_bug.cgi?id=1844781

### PR DESCRIPTION
**Pull request by DerekVeit**
Fix #1095

### CODE REVIEW

**Review by buhtz — APPROVED** [review]
Hello Derek,
On behalf of the team, thank you for your contribution and taking
the time to improve Back In Time. We appreciate it.

Your PR will be merged in some days.

See [What happens after you opened a Pull Request (PR)?](https://github.com/bit-team/backintime/blob/dev/CONTRIBUTING.md#what-happens-after-you-opened-a-pull-request-PR) in our FAQ about our usual policy.

Best,
Christian

**Comment by buhtz** [comment]
Forget it myself. Please add a line to the CHANGES file. Something like this:

    fix(gui): Fix Qt segmentation fault with uninstall ExtraMouseButtonEventFilter when closing main window (#1095)

**Comment by DerekVeit** [comment]
Thanks, Christian.  I hope I understood correctly.  I amended that to the previous commit.  Feel free to point out anything I do not quite right.  I'll be happy to revise again.  I hope to be making more contributions.

**Review by buhtz — APPROVED** [review]

**Comment by buhtz** [comment]
I used your script and confirm it might work. With your fix I can start-stop BIT 1000 times without seg fault. But without the fix I do have ~50% of seg faults.

**Comment by DerekVeit** [comment]
I tried it with and without the fix on a few different versions, with Python 3.8, 3.10, 3.12 and BIT 1.2.1, 1.3.2, 1.4.3, 1.4.4-dev (not every combination).  I didn't keep statistics, but without the fix, I got segfaults roughly half the time except with 1.4.4-dev and Qt6.  With the Qt6 build, the segfaults were much less frequent but did still happen.

It seems there must be some race in the QApplication destruction that determines whether it will have the segfault, and that timing is a bit different with my Qt6 build.  Little things, like whether files are in cache, seem to affect it.

But with the fix, I never got a segfault on any version.

**Pull request merged**
