### PR TITLE
fix: Copy symlink as symlink in snapshot compare

### LINKED ISSUE #1902: Comparing 2 snapshots can fill your disk if it includes a symlink to e.g. `/` (doesn't copy symlink as symlink)
First of all thanks for the software, have been using it quite a bit through the years!

I was trying to compare 2 snapshots (one of <30GB with one of a few 100MB) and suddenly noticed my system acting weird due to what turned out to be my disk being full, even though nearly 1TB of 1.8TB was free beforehand...

Long story short, it turned out that symlinks in the snapshots were having their targets copied as a regular dir (instead of being copied as symlinks themselves) to the temp location BiT uses for comparing.  The symlink's target included another symlink somewhere within, this one pointing to `/` (Proton install from Steam which has a `z:` drive/symlink pointing to `/`).  That resulted in an infinite dir structure being copied: `/` includes `~/.steam/root/steamapps/compatdata/ID/pfx/dosdevices/z:` which points to `/` which includes `~/.steam/root/steamapps/compatdata/ID/pfx/dosdevices/z:` which points to ...

After digging into the source a bit it seems that BiT creates a copy of the snapshots its comparing ( https://github.com/bit-team/backintime/blob/11006532ee983e96632b0573c8f707329e9802da/qt/snapshotsdialog.py#L370 and line 372).  This uses Python's `shutil.copytree` ( https://github.com/bit-team/backintime/blob/11006532ee983e96632b0573c8f707329e9802da/qt/app.py#L1700 ) which by default (and in the form BiT calls it) doesn't copy symlinks as symlinks but copies their targets:

> If `symlinks` is true, symbolic links in the source tree are represented as symbolic links in the new tree and the metadata of the original links will be copied as far as the platform allows; if false or omitted, the contents and metadata of the linked files are copied to the new tree.  [Default is `False`]
> -- https://docs.python.org/3/library/shutil.html#shutil.copytree

presumably causing the issue.

Easy reproduction of the base issue:
  * Create 2 snapshots, at least one of them containing a symlink
  * Compare the 2 snapshots
  * Check the temp dir of the snapshots and notice there is no symlink but the target is included instead
    * E.g.:
      
       ```sh
       $ ls -l ~/backup_source/
       total 0
       lrwxrwxrwx 1 USER users 3 10-12 15:16 bar -> foo
       -rw-r--r-- 1 USER users 0 10-12 15:48 baz
       -rw-r--r-- 1 USER users 8 10-12 15:48 foo

       $  ls -l ~/backup_target/backintime/HOST/USER/PROFILE_NAME/last_snapshot/backup/home/USER/backup_source/
       total 4
       lrwxrwxrwx 2 USER users 3 10-12 15:16 bar -> foo
       -rw-r--r-- 1 USER users 0 10-12 15:48 baz
       -rw-r--r-- 2 USER users 8 10-12 15:48 foo

       $ ls -l /tmp/tmp*/backup_source/
       /tmp/tmpebgjzrbp_20241012-154851-538/backup_source/:
       total 8
       -rw-r--r-- 1 USER users 8 10-12 15:48 bar
       -rw-r--r-- 1 USER users 8 10-12 15:48 foo

       /tmp/tmpfvmhdn16_20241012-154902-833/backup_source/:
       total 8
       -rw-r--r-- 1 USER users 8 10-12 15:48 bar
       -rw-r--r-- 1 USER users 0 10-12 15:48 baz
       -rw-r--r-- 1 USER users 8 10-12 15:48 foo
       ```

To probably reproduce the exact situation (NOT RECOMMENDED!), written from memory as I don't want to try it again to verify:
  * Have 2 snapshots that somewhere (indirectly) include a symlink to `/` (e.g. Steam with a Proton install or a regular Wine environment)
    * *NOTE:* my snapshots didn't have a direct symlink to `/`.  The snapshot included my `~/.steam` which has a `root -> /home/USER/.local/share/Steam` symlink but `~/.local/share/Steam` itself is excluded from the snapshots (wouldn't matter here as the symlink uses an absolute path so it points to the live data, not the snapshot's).
       * And `/home/USER/.local/share/Steam` includes content that has symlinks pointing to `/`.
  * Compare the 2 entire snapshots
    * This will fill up `/tmp`.
  * If `/tmp` if not a `tmpfs` that disk should now be full
  * In case `/tmp` is a `tmpfs` (it is in my case), now fill up an actual disk:
    * Now that `/tmp` is full, kill Back in Time
    * Start a new Back in Time and compare the 2 snapshots again, it will now use `/var/tmp` (presumably because `/tmp` is now full so Python will pick something else for its temp location)
    * Let it fill `/var/tmp` and enjoy the disk being full
  * Once satisfied, manually cleanup the temp BiT content in `/tmp` and `/var/tmp` to get a sane system again

<details>
<summary>`backintime --diagnostics`</summary>

```json
{
    "backintime": {
        "name": "Back In Time",
        "version": "1.4.3",
        "latest-config-version": 6,
        "local-config-file": "/home/UsernameReplaced/.config/backintime/config",
        "local-config-file-found": true,
        "global-config-file": "/etc/backintime/config",
        "global-config-file-found": false,
        "started-from": "/usr/share/backintime/common",
        "running-as-root": false,
        "user-callback": "/home/UsernameReplaced/.config/backintime/user-callback",
        "keyring-supported": true
    },
    "host-setup": {
        "platform": "Linux-6.11.2-1-default-x86_64-with-glibc2.40",
        "system": "Linux #1 SMP PREEMPT_DYNAMIC Fri Oct  4 17:37:58 UTC 2024 (38c846e)",
        "OS": "openSUSE Tumbleweed",
        "display-system": "tty",
        "locale": "en_US, UTF-8",
        "PATH": "/home/UsernameReplaced/.local/bin:/home/UsernameReplaced/.local/bin:/home/UsernameReplaced/.local/bin:/usr/local/bin:/usr/bin:/bin",
        "RSYNC_OLD_ARGS": "(not set)",
        "RSYNC_PROTECT_ARGS": "(not set)"
    },
    "python-setup": {
        "python": "3.11.10 main Sep 09 2024 17:03:08 CPython GCC",
        "python-executable": "/usr/bin/python3",
        "python-executable-symlink": true,
        "python-executable-resolved": "/usr/bin/python3.11",
        "sys.path": [
            "/usr/share/backintime/qt/plugins",
            "/usr/share/backintime/common/plugins",
            "/usr/share/backintime/plugins",
            "/usr/share/backintime/common",
            "/usr/lib64/python311.zip",
            "/usr/lib64/python3.11",
            "/usr/lib64/python3.11/lib-dynload",
            "/usr/lib64/python3.11/site-packages",
            "/usr/lib64/python3.11/_import_failed",
            "/usr/lib/python3.11/site-packages"
        ],
        "qt": {
            "Version": "PyQt 5.15.10 / Qt 5.15.15",
            "Theme": "hicolor",
            "Theme Search Paths": [
                "/usr/share/icons",
                ":/icons"
            ],
            "Fallback Theme": "hicolor",
            "Fallback Search Paths": [
                "/usr/share/pixmaps"
            ]
        }
    },
    "external-programs": {
        "rsync": {
            "version": "3.3.0",
            "protocol": "31.0",
            "capabilities": {
                "file_bits": 64,
                "inum_bits": 64,
                "timestamp_bits": 64,
                "long_int_bits": 64,
                "socketpairs": true,
                "symlinks": true,
                "symtimes": true,
                "hardlinks": true,
                "hardlink_specials": true,
                "hardlink_symlinks": true,
                "IPv6": true,
                "atimes": true,
                "batchfiles": true,
                "inplace": true,
                "append": true,
                "ACLs": true,
                "xattrs": true,
                "secluded_args": "optional",
                "iconv": true,
                "prealloc": true,
                "stop_at": true,
                "crtimes": false
            },
            "optimizations": {
                "SIMD_roll": true,
                "asm_roll": false,
                "openssl_crypto": true,
                "asm_MD5": false
            },
            "checksum_list": [
                "xxh128",
                "xxh3",
                "xxh64",
                "md5",
                "md4",
                "sha1",
                "none"
            ],
            "compress_list": [
                "zstd",
                "lz4",
                "zlibx",
                "zlib",
                "none"
            ],
            "daemon_auth_list": [
                "sha512",
                "sha256",
                "sha1",
                "md5",
                "md4"
            ]
        },
        "ssh": "OpenSSH_9.9p1, OpenSSL 3.1.4 24 Oct 2023",
        "sshfs": "3.7.4a",
        "encfs": "1.9.5",
        "shell": "/bin/bash",
        "shell-version": "GNU bash, version 5.2.37(1)-release (x86_64-suse-linux)"
    }
}
```

</details>

Original problem on openSUSE Tumbleweed (installed from the main repo, diagnostics included above), basic issue reproduced on Slackware (Back in Time 1.4.3, Python 3.11.10, installed via slackbuilds.org).

### PR DESCRIPTION
**Pull request by sevens**
When comparing snapshots, copy symlinks in the snapshots as symlinks, not as
their target.  The old behavior made the comparison not fully compare the actual
snapshot data and, even worse, could fill up your entire disk (when having
circular symlinks, e.g. a symlink to `/`, which copies `/` and eventually
copies the original symlink which points to `/` which ...).

Additionally fixes a crash when the compared snapshot(s) contain a symlink
pointing to a nonexistent target.

Fixes #1902.

### CODE REVIEW

**Comment by sevens** [comment]
I couldn't find any relevant unittests (in fact, `qt/tests/` seems to only have a basic lint test for the whole `qt/` side; otherwise I'd have tried to at least add a unittest for `app.MainWindow.tmpCopy()` itself).

Did some manual testing.

Snapshot with regular symlink:
1. Setup:
   * Have backup source with at least one (valid) symlink
     ```sh
     $  ls -l backup_source/
     total 4
     lrwxrwxrwx 1 user users 3 11-19 16:58 bar -> foo
     -rw-r--r-- 1 user users 4 11-19 17:00 foo
     ```

   * Create 2 snapshots.  These do have the symlink in tact:
     ```sh
     $  ls -l backup_target/backintime/host/user/1/last_snapshot/backup/home/user/dev/external/backintime/test.no-git/fake_home/backup_source/
     backup_source/
     total 4
     lrwxrwxrwx 2 user users 3 11-19 16:58 bar -> foo
     -rw-r--r-- 1 user users 4 11-19 17:00 foo
     ```

2. Test without this fix
   * Compare the 2 snapshots in the GUI, using `Backup -> Compare snapshots...` (pick one snapshot from the list in the main view, pick the other from the drop-down right to the `Compare` button at the bottom)
   * Check temp copies in shell:
     ```sh
     $  ls -l /tmp/tmp*/backup_source
     /tmp/tmpedqq05c8_20241119-170042-790/backup_source:
     total 8
     -rw-r--r-- 1 user users 4 11-19 17:00 bar
     -rw-r--r-- 1 user users 4 11-19 17:00 foo

     /tmp/tmpjl7xix7a_20241119-165907-278/backup_source:
     total 0
     -rw-r--r-- 1 user users 0 11-19 16:58 bar
     -rw-r--r-- 1 user users 0 11-19 16:58 foo
     ```
   * The symlinks are now replaced with their targets (this results in a full disk if you have (eventually) circular symlinks, like something in your home pointing to `/` or even just your home)

3. Test with this fix
   * Compare the 2 snapshots, same way as above
   * Check in shell:
     ```sh
     $  ls -l /tmp/tmp*/backup_source/
     /tmp/tmp6f5bpc2q_20241119-170042-790/backup_source/:
     total 4
     lrwxrwxrwx 1 user users 3 11-19 16:58 bar -> foo
     -rw-r--r-- 1 user users 4 11-19 17:00 foo

     /tmp/tmpykrspljt_20241119-165907-278/backup_source/:
     total 0
     lrwxrwxrwx 1 user users 3 11-19 16:58 bar -> foo
     -rw-r--r-- 1 user users 0 11-19 16:58 foo
     ```

Snapshot with broken symlink (pointing to nonexistent target):
1. Setup
   * Have a backup source with a 'broken' symlink (pointing to a nonexistent target):
     ```sh
     $  ls -l backup_source/
     total 4
     lrwxrwxrwx 1 user users  3 11-19 16:58 bar -> foo
     lrwxrwxrwx 1 user users 11 11-21 11:26 baz -> nonexistent
     -rw-r--r-- 1 user users  4 11-19 17:00 foo
     ```

   * Create 2 snapshots.  These do have the symlink in tact:
     ```sh
     $  ls -l backup_target/backintime/host/user/1/last_snapshot/backup/home/user/dev/external/backintime/test.no-git/fake_home/backup_source/
     total 4
     lrwxrwxrwx 1 ephedio users  3 11-19 16:58 bar -> foo
     lrwxrwxrwx 1 ephedio users 11 11-21 11:26 baz -> nonexistent
     -rw-r--r-- 1 ephedio users  9 11-21 11:26 foo
     ```

2. Test without this fix
   * Compare the 2 snapshots, same way as above
   * App now crashes:
     ```
     Traceback (most recent call last):
       File "/home/user/dev/external/backintime/qt/snapshotsdialog.py", line 370, in btnDiffClicked
         path1 = self.parent.tmpCopy(path1, sid1)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
       File "/home/user/dev/external/backintime/qt/app.py", line 1725, in tmpCopy
         shutil.copytree(full_path, tmp_file)
       File "/usr/lib64/python3.11/shutil.py", line 573, in copytree
         return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
       File "/usr/lib64/python3.11/shutil.py", line 527, in _copytree
         raise Error(errors)
     shutil.Error: [('/home/user/dev/external/backintime/test.no-git/fake_home/backup_target/backintime/host/user/1/20241121-112648-601/backup/home/user/dev/external/backintime/test.no-git/fake_home/backup_source/baz', '/tmp/tmpvvv2e1nz_20241121-112648-601/backup_source/baz', "[Errno 2] No such file or directory: '/home/user/dev/external/backintime/test.no-git/fake_home/backup_target/backintime/host/user/1/20241121-112648-601/backup/home/user/dev/external/backintime/test.no-git/fake_home/backup_source/baz'")]
     /home/user/dev/external/backintime/test.no-git/../qt/backintime-qt: line 31:  5568 Aborted                 /usr/bin/env python3 -Es ${APP_PATH}/app.py "$@"
     ```

3. Test with this fix
   * Compare the 2 snapshots, same way as above
   * App now doesn't crash and has the broken symlink in tact as well:
     ```sh
     $  ls -l /tmp/tmp*/backup_source/
     /tmp/tmpcahq_g0n_20241121-112635-905/backup_source/:
     total 4
     lrwxrwxrwx 1 user users  3 11-19 16:58 bar -> foo
     lrwxrwxrwx 1 user users 11 11-21 11:26 baz -> nonexistent
     -rw-r--r-- 1 user users  4 11-19 17:00 foo

     /tmp/tmprs7_uauk_20241121-112648-601/backup_source/:
     total 4
     lrwxrwxrwx 1 user users  3 11-19 16:58 bar -> foo
     lrwxrwxrwx 1 user users 11 11-21 11:26 baz -> nonexistent
     -rw-r--r-- 1 user users  9 11-21 11:26 foo
     ```

**Comment by sevens** [comment]
I also checked if there were any other `copytree()` usages in the source that might need the same fix, couldn't find any usages at all.

**Comment by buhtz** [comment]
Hello Peter,
On behalf of the team, thank you for your contribution and taking the time to improve Back In Time. We appreciate it.

Your PR will be reviewed as soon as possible.

To find out how we usually tread PRs please read ["What happens after you opened a PullRequest (PR)?"](https://github.com/bit-team/backintime/blob/dev/CONTRIBUTING.md#what-happens-after-you-opened-a-pull-request-PR).

Best,
Christian

**Comment by buhtz** [comment]
Great work. I appreciate that. Ready to merge.

**Pull request merged**
