### PR TITLE
doc: Add Synology DSM version 7 to the FAQs

### PR DESCRIPTION
**Pull request by Silver-Saucepan**
Add instructions on how to configure Synology devices running DSM7 for use with SSH-mode BIT profiles

### CODE REVIEW

**Comment by aryoda** [comment]
@Silver-Saucepan Thanks a lot for your contribution!

Your PR is related to  #1674 (where I wanted to write a FAQ entry too) and does save me a lot of time now :-)

Would it be possible to check if Synology's Audio Station shows a wrong "used disk" size for the backup folder (since it seems to follow the links too instead of ignoring them = effectivly overcounting the used disk size...)

**Comment by Silver-Saucepan** [comment]
@aryoda Yes, when Synology's File Station calculates the size of a folder it does not seem to be inode-number-aware, so each hard link within the folder is treated as a separate file, even if it links to a file who's size it has already counted, and so its size is added to the total. Thus the calculated size of a BIT snapshots folder can be many times its actual space usage on disk.

You might know this already but, the GNU ```du``` command does seem to be inode-number-aware and so can be used to get the actual space usage, counting additional hard links to a file it has already encountered as zero size.  e.g. if the snapshots are in a folder called ```1``` then ```du -hs 1/``` shows the actual space used.  However, if you use ```du``` on an individual snapshot folder (e.g. ```du -hs 1/20240819-061501-243``` it includes the size of 'files' that are actually hard-links to files in other snapshots.

This should probably be described in the DSM 7 section of the FAQs, and DSM 6 probably has the same behaviour but I can't test it to be sure.

**Comment by buhtz** [comment]
Would it be OK if I merge this?

**Comment by Silver-Saucepan** [comment]
It's OK by me. I tested it on a NAS running DSM 7.2.1

**Comment by buhtz** [comment]
> It's OK by me. I tested it on a NAS running DSM 7.2.1

Thank you very much. This helps a lot.

**Pull request merged**
