### PR TITLE
Update all version numbers to 1.3.3-dev for development of upcoming release

### PR DESCRIPTION
**Pull request by aryoda**
* Exception: Debian changelog file is left as-is (will be changed when it is used for a release)

I have used semantic versioning (which allows labels), see: https://semver.org/#spec-item-9

### CODE REVIEW

**Comment by buhtzz** [comment]
Not sure but maybe this files are also relevant

 - The sphinx config `common/doc-dev/conf.py`
 - Qt `qt/docbook/en/index.docbook` (no idea what this file is about)
 - four manpage files in `qt/man/C/*` and `common/man/C/*`
 - [`common/config.py`](https://github.com/bit-team/backintime/blob/4b09eba80237d64b84a3ed2c4aba1c440bc5ae84/common/config.py#L52)
 
About Debian.
This is OK for me to leave it as it is. I assume Germar used this for launchpad releasing an Ubuntu package.
I will discuss this after the next release with the Debian package maintainers. Distro specific files shouldn't exist in an upstream repo. And the Python Debian Team has it's [own GitLab server](https://salsa.debian.org/) to organize things like that. Back In Time just need to migrate into there.

**Comment by emtiu** [comment]
> Not sure but maybe this files are also relevant
> 
> * The sphinx config `common/doc-dev/conf.py`
> * Qt `qt/docbook/en/index.docbook` (no idea what this file is about)
> * four manpage files in `qt/man/C/*` and `common/man/C/*`
> * [`common/config.py`](https://github.com/bit-team/backintime/blob/4b09eba80237d64b84a3ed2c4aba1c440bc5ae84/common/config.py#L52)

Let's update those as well, then I'll be happy to commit. Bonus points if we find out what the docbook file is about ;)

**Comment by aryoda** [comment]
I'll update and push tonight (did only search for "1.3.2" but obviously we have more old version numbers in other files).

We should use a central "update version number" bash script to update all files consistently...

**Comment by aryoda** [comment]
This script will also update the debian/changelog but who will be the maintainer now?

https://github.com/bit-team/backintime/blob/de138677077031079d854f63f3cf0117fde91e9b/updateversion.sh#L7

**Comment by emtiu** [comment]
For the moment, it's probably appropriate to name the "BiT team". We just don't have an email address ;)

**Comment by buhtzz** [comment]
I assume this file is relevant only for Ubuntu Universe (the "community" repos; launchpad). [Debian don't track](https://tracker.debian.org/pkg/backintime) the upstream maintainer.

We should move the discussion about Ubuntu-maintainment to our mailing list.

**Comment by aryoda** [comment]
I think I have caught now all version numbers spread in different files.

I have also fixed a bug in `updateversion.sh` and put doc and TODO comments into it...

**Review by buhtzz — APPROVED** [review]

**Pull request merged**
