### PR TITLE
#1297 Issue: Updated logger.py and snapshots.py

### PR DESCRIPTION
**Pull request by rahulsamant37**
I have corrected the snapshot.py

and for common :: logger.py

I have improve the code by adding textwrap.wrap()

Did you run "codespell"?

### CODE REVIEW

**Comment by buhtz** [comment]
Thank you. But please explain what you did and why.

You did not run unit Tests.

Have you read contributing.md?

And has nothing to do with #1297

**Comment by rahulsamant37** [comment]
Sorry, if I made a mistake I'm doing it for the first time that's why I might had made some mistake. I will definitely take this as consideration for my future aspects.

**Comment by buhtz** [comment]
Hello rahulsamant37,
thank you for your reply. I appreciate that.

We often have to deal with spammers, star abuse and people copy and pasting AI content as a PR. It is not easy to distinguish between a low skilled contributor and a spammer.

Next time...

Please read the CONTRIBUTING.md file carefully. This file is not only about technical details but also about the "spirit" of the project and its workflow.

The issue number (#1297) you used in your PR has nothing to do with the modifications you provide in your PR.

Describe why you made the modifications and what is your intention. It is not clear to me by just reading the "Files changed" section.

Your modifications do touch two totally separate topics (logging output & smart remove feature). Don't mix PRs like that. Keep them simple.

Best,
Christian

**Comment by rahulsamant37** [comment]
Thank you for guiding me in the right direction. I understand it must be difficult for you to handle this, and I'm genuinely thankful to you for guiding me.

**Pull request closed without merging**
